
on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

  schedule:
    - cron: "0 0 * * 6" # every weekend

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64, aarch64]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3

      - uses: jirutka/setup-alpine@v1
        id: alpine
        with:
          arch: ${{ matrix.arch }}
          branch: edge
          extra-keys: ./beni-64e2a1a5.rsa.pub
          packages: alpine-sdk

      - name: Setup keys & perms
        run: |
          cp -v ./abuild.conf ./beni-64e2a1a5.rsa.pub /etc/
          echo '${{ secrets.PKG_PRIV_KEY }}' > /etc/beni-64e2a1a5.rsa
          echo 'PACKAGER_PRIVKEY="/etc/beni-64e2a1a5.rsa"' >> /etc/abuild.conf
          chown runner /etc/beni-64e2a1a5.rsa*
          adduser runner abuild
        shell: alpine.sh --root {0}

      # Runs a single command using the runners shell
      - name: Build packages
        run: ./ci.sh
        shell: alpine.sh {0}

      # Runs a set of commands using the runners shell
      - name: Show output
        run: tree -a ${{ steps.alpine.outputs.root-path }}/home/runner/packages/beni/

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.arch }}
          path: ${{ steps.alpine.outputs.root-path }}/home/runner/packages/beni/${{ matrix.arch }}

  upload:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/download-artifact@v3
        with:
          path: beni/
      - run: tree -a
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_S3_ENDPOINT: ${{ secrets.AWS_S3_ENDPOINT }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: beni
